ALTER TABLE packages
ADD COLUMN IF NOT EXISTS name VARCHAR(255),
ADD COLUMN IF NOT EXISTS type VARCHAR(255),
ADD COLUMN IF NOT EXISTS amount DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "seedAmount" DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "seedType" VARCHAR(255),
ADD COLUMN IF NOT EXISTS period INTEGER,
ADD COLUMN IF NOT EXISTS "collectionDays" VARCHAR(255),
ADD COLUMN IF NOT EXISTS duration INTEGER,
ADD COLUMN IF NOT EXISTS benefits JSON,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS status VARCHAR(255),
ADD COLUMN IF NOT EXISTS "merchantId" INTEGER,
ADD COLUMN IF NOT EXISTS "dateCreated" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "maxCustomers" INTEGER,
ADD COLUMN IF NOT EXISTS "currentCustomers" INTEGER,
ADD COLUMN IF NOT EXISTS "interestRate" DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS "minimumSavings" DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "savingsFrequency" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "extraCharges" DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "defaultPenalty" DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "defaultDays" INTEGER,
ADD COLUMN IF NOT EXISTS "loanAmount" DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "loanInterestRate" DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS "loanPeriod" INTEGER,
ADD COLUMN IF NOT EXISTS "defaultAmount" DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "gracePeriod" INTEGER,
ADD COLUMN IF NOT EXISTS "loanCharges" DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS "packageCategory" VARCHAR(255);

-- Basic FK for merchantId if not present
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'packages_merchantId_fkey'
  ) THEN
    ALTER TABLE packages
    ADD CONSTRAINT packages_merchantId_fkey
    FOREIGN KEY ("merchantId") REFERENCES merchants(id) ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;
END $$;


